name: Chris Schuchmann
favicon: null
layout_spectrum: 0.05120692169293761
typography_spectrum: 0.6982971772085875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#0f0f11'
    - '#d1bda4'
    - '#90816a'
    - '#ba1a36'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.4326837509870529
  rhythmicContrast: 0.32930844463407993
purpose: []
